require 'rubygems'
require 'rack'
require 'active_record'
require 'clearance'
require 'addressable/uri'

require 'openid'
require 'openid/store/filesystem'
require 'openid/extensions/sreg'

require 'checkpoint/idcheck'
require 'checkpoint/authentication'
require 'checkpoint/openid_server'
require 'checkpoint/sessions'
require 'checkpoint/user'
require 'checkpoint/consumer'
